### ISSUE TITLE
有几个小问题

### ISSUE THREAD

**Issue by mumusa** [RocketsChen/CDDStore#1]
1.商品详情页面pop后无法dealloc，DCGoodBaseViewController的block有循环引用；
2.商品详情无法手势返回，可以考虑继承UIScrollview自定义类，再重写gestureRecognizerShouldBegin来根据contentoffset判断；
3.个人中心的导航条在push和pop的时候太生硬，可以考虑通过透明度加动画来优化；
4.statusstyle，如果想做成light，然后再在自定义NavController里面重写preferredStatusBarStyle和childViewControllerForStatusBarStyle；
最后，看完项目，收获很多，笔芯小哥

**Comment by RocketsChen** [comment]
不错的建议，已采纳。循环引用已解决~
