### ISSUE TITLE
商品详情这块我不清楚怎么传商品id？

### ISSUE THREAD

**Issue by NOMBER2011** [RocketsChen/CDDStore#12]
<img width="509" alt="2017-12-15 13 08 32" src="https://user-images.githubusercontent.com/13688441/34027654-138391f0-e199-11e7-8e02-5dcaf21b2d18.png">
在这个界面我需要用到商品id，就是从上个界面传过来的，但是我现在在这4个controller打印商品id，log显示为空的，这个怎么传至

**Comment by NOMBER2011** [comment]
我刚才看了你的这个（CDDPagerController）我会了，你的项目写的很好，持续关注中

**Comment by RocketsChen** [comment]
1.DCGoodsSetViewController控制器的`didSelectItemAtIndexPath`方法中 
通过模型给DCGoodDetailViewController控制器传值过去
2.DCGoodDetailViewController的`setUpChildViewControllers`方法中给详情的父类DCGoodParticularsViewController传过去这样就可以获取到你所需的商品信息了~
