### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Kevinsamer** [RocketsChen/CDDStore#14]
你好，我刚刚开始学习IOS开发，下载解压后项目编译出错，错误如题，请问是怎么回事啊？

**Comment by RocketsChen** [comment]
Bitcode 更改无效的话可以尝试找到Build settings->Linking->Other Linker Flags
将此属性修改成-all_load
或者尝试把Other Linker Flags下的属性全部删除

**Comment by RocketsChen** [comment]
Bitcode 更改无效的话可以尝试找到Build settings->Linking->Other Linker Flags
将此属性修改成-all_load
