### ISSUE TITLE
O(∩_∩)O谢谢

### ISSUE THREAD

**Issue by Ya0HJ** [RocketsChen/CDDStore#16]
首先很高兴收到您的回复。
可能是我刚才表达的不够清楚。我想问的是在DCFeatureitem.h这个文件里面的list这个属性。您的本地plist文件里面的的list数组里面的数据结构是[item0 {infoname:黑色, plusprice:0}]
我的数据结构是[黑色，红色，蓝色]。
在这里不知道怎么修改，请指教。

**Comment by RocketsChen** [comment]
例如 你没有具体infoname，plusprice字段，你可以在模型这样处理
`@property (nonatomic , strong) NSArray<NSString *> *colorArray;` colorArray为你这一数组名
赋值的时候 `cell.Item = _Item[indexPath.section].colorArray[indexPath.row]; ` 就可以了，大同小异。

**Comment by Ya0HJ** [comment]
O(∩_∩)O谢谢

**Comment by Ya0HJ** [comment]
大佬，我刚才试了一下。发现好多地方都取不到值。或者是类型不对。不知道大神有没有时间帮我改一下？O(∩_∩)O谢谢

**Comment by RocketsChen** [comment]
邮箱📮

**Comment by Ya0HJ** [comment]
497661841@qq.com   O(∩_∩)O谢谢大佬。
