### ISSUE TITLE
商品选择页面有没有实现质数选择？

### ISSUE THREAD

**Issue by FaDeve** [RocketsChen/CDDStore#2]

**Comment by RocketsChen** [comment]
请说的详细点~

**Comment by FaDeve** [comment]
就是比如点击32尺码，其他尺码会置灰不可点击，然后只剩下红色，再点回32尺码，其他尺码恢复点击，有红色蓝色，你看看淘宝客户端逻辑


原始邮件
发件人:RocketsChennotifications@github.com
收件人:RocketsChen/CDDStoreCDDStore@noreply.github.com
抄送:FaDeve2404445663@qq.com; Authorauthor@noreply.github.com
发送时间:2017年8月8日(周二) 11:19
主题:Re: [RocketsChen/CDDStore] 商品选择页面有没有实现质数选择？ (#2)


请说的详细点~

**Comment by RocketsChen** [comment]
采取建议，以实现属性质数选择，至于点击某个变色其余变灰需根据后台返回数据联动，前端属性Item的点击已处理好~~~如有更好的建议欢迎Issues
