### ISSUE TITLE
感谢分享，一些小建议

### ISSUE THREAD

**Issue by Jax1993** [RocketsChen/CDDStore#24]
很不错的项目，作者很用心，很多细节都实现得很漂亮。  
在使用过程中，有一些个人感受跟你分享一下。  
主要是编码风格，我认为应该使用更符合 Apple 规范的编码风格，这样大家写代码会更统一， 参考[禅与 Objective-C 编程艺术 ](https://github.com/oa414/objc-zen-book-cn) 和 [Introduction to Coding Guidelines for Cocoa](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/CodingGuidelines.html)。  
另外，ViewController 的代码组织可以更加模块化一些，比如生命周期，代理，其他辅助方法这样模块区分。
感谢分享。

**Comment by Jax1993** [comment]
另外，UI 响应后的业务逻辑最好不用放在 View 里面，可以用 delegate 的形式将事件传递回 Controller。

**Comment by RocketsChen** [comment]
非常感谢你对开源阅读，业务逻辑和起初项目设计的开发模式有很大的关系，之前为了方便阅读使用的MVC，如果要剥离业务层的把建议使用MVVM，后续如果更新我也会尝试新的架构模式。
