### ISSUE TITLE
git后无法运行时咋回事？

### ISSUE THREAD

**Issue by aynstan** [RocketsChen/CDDStore#3]
Apple Mach-O Linker Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RocketsChen** [comment]
我这边没发现这个问题~

**Comment by RocketsChen** [comment]
遇到楼上问题，把Active Architeture only 设置为No就好了，这里解释的为什么我项目中原先没有设置，设Active Architeture only置为NO的时候，会编译支持的所有的版本
设置为YES的时候，是为Debug的时候速度更快，但它只编译当前的architecture 版本

**Comment by Kevinsamer** [comment]
改了还是编译不通过呢

**Comment by RocketsChen** [comment]
更改之后关闭，重新打开运行
