### ISSUE TITLE
像商品详情的那种通知是不是移除，如果从商品详情控制器再push一个商品详情，是不是有很多问题

### ISSUE THREAD

**Issue by NK-iOS** [RocketsChen/CDDStore#5]
像商品详情的那种通知是不是移除，如果从商品详情控制器再push一个商品详情，是不是有很多问题

**Comment by RocketsChen** [comment]
我界面通知采取的异步操作，其次我在界面的dealloc方法中移除了通知。当然在理论上，代理和block都可以代替通知功能需求，至于你说的很多问题，如果你发现了还请Issue我很乐意去解决~

**Comment by NK-iOS** [comment]
比如通知不移除的话，在当前商品详情页再push一个商品详情页，当第二个商品详情页发出通知时，不是所有商品详情页都能收到通知了？
