### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by maboyi** [RocketsChen/CDDStore#9]
首先表示一下对楼主的敬仰，demo很棒。
发现了商品详情页无法dealloc，是因为在注册通知那里dcNewFeaVc.goodImageView = _goodImageView;循环引用导致。
另外，如果从商品详情跳到购物车，再跳到一个新的商品详情，点击加入购物车，筛选参数的view就会出现后立即移除，好像也是通知影响的。

**Comment by RocketsChen** [comment]
循环已解决，通知影响我暂无发现，下载最近还有问题欢迎issue
